-- MySQL Script generated by MySQL Workbench
-- Tue Oct 16 20:08:49 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema DB_courses
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DB_courses
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DB_courses` DEFAULT CHARACTER SET utf8 ;
USE `DB_courses` ;

-- -----------------------------------------------------
-- Table `DB_courses`.`administrators`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_courses`.`administrators` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_courses`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_courses`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_courses`.`courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_courses`.`courses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  `price` FLOAT NOT NULL,
  `categoriy` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_courses_categories_idx` (`categoriy` ASC),
  CONSTRAINT `fk_courses_categories`
    FOREIGN KEY (`categoriy`)
    REFERENCES `DB_courses`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
