-- MySQL Script generated by MySQL Workbench
-- Tue Oct 16 18:22:45 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema DB_courses
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DB_courses
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DB_courses` DEFAULT CHARACTER SET utf8 ;
USE `DB_courses` ;

-- -----------------------------------------------------
-- Table `DB_courses`.`administrators`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_courses`.`administrators` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_courses`.`courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_courses`.`courses` (
)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
